openapi: 3.1.0
info:
  version: 1.0.0
  title: Psychologist app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of psychologist app
tags:
  - name: Psychologist
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://psychologist-app.vercel.app
paths:
  /psychologist/{id}:
    get:
      $ref: ../swagger/paths/id/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
